alias gs='git status'
alias ga='git add'
alias gp='git push'
alias gd='git diff'
alias gb='git branch'
alias gl='git log'
alias gdbr='git delete-branch'
alias gc='git commit'
alias gcm='git commit -m'
alias gcam='git commit -am'
alias gf='git fetch'
alias gam='git commit --amend'

