---
- hosts: 127.0.0.1
  connection: local
  gather_facts: false

  tasks:
    - name: Install apt packages for work
      become: true
      apt:
        name: "{{ package }}"
      vars:
        package:
          - pwgen
          - postgresql-client
