---
- hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Run apt-get update
    become: true
    ignore_errors: yes
    apt:
      update_cache: yes
  - name: Install apt packages
    become: true
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - git
      - vim
      - tmux
      - bat

