---
- hosts: 127.0.0.1
  connection: local
  gather_facts: false
  vars_files:
    - vars.yaml

  tasks:
    - name: Upgrade all packages to their latest version
      become: true
      apt:
        name: "*"
        state: latest
    - name: Install apt packages
      become: true
      apt:
        name: "{{ package }}"
      vars:
        package:
          - git
          - vim
          - tmux
          - htop
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - build-essential
          - zsh
          - stow
          - npm
          - fzf
          - exuberant-ctags
          - jq
          - clang
          - ripgrep
          - net-tools
          - shellcheck
          - shfmt
          - fd-find
          - lookatme
          - pipx
          - xclip  # for yanking to clipboard in nvim
    - name: Install ansible collection
      shell: ansible-galaxy collection install community.general && ansible-galaxy collection install community.crypto

    # Configurate repo with this configs
    - name: Set ssh remote origin url
      community.general.git_config:
        scope: local
        repo: ~/configs
        name: remote.origin.url
        value: git@github.com:akili/configs.git

    # SSH
    - name: Create folder for ssh
      file:
        path: ~/.ssh
        state: directory
    - name: Generate an OpenSSH keypair
      community.crypto.openssh_keypair:
        path: ~/.ssh/id_rsa

    # Docker
    - name: Add apt-key
      become: true
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
    - name: Add docker repo
      become: true
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
    - name: Install docker
      become: true
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: yes
    - name: Add user permissions
      become: true
      shell: usermod -aG docker {{ lookup('env','USER') }}

    # Pipx
    - name: Install some packages with pipx
      vars:
        pipx_packages:
          - pyright
          - ruff
          - pre-commit
          - poetry
      community.general.pipx:
        name: "{{ item }}"
        state: latest
      with_items: "{{ pipx_packages }}"

    # uv
    - name: Install uv
      shell: curl -LsSf https://astral.sh/uv/install.sh | sh

    # zsh
    - name: Make zsh default shell
      become: true
      shell: chsh -s /usr/bin/zsh akili
    - name: Register oh-my-zsh folder
      stat:
        path: ~/.oh-my-zsh
      register: ohmyzsh
    - name: Install oh-my-zsh
      shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      when: not ohmyzsh.stat.exists
    - name: Install zsh-syntax-highlightin
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    - name: Install zsh-autosuggestions
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    - name: Write down all plugins
      lineinfile:
        path: ~/.zshrc
        search_string: plugins=(git
        line: plugins=(git docker docker-compose command-not-found common-aliases zsh-autosuggestions zsh-syntax-highlighting poetry fzf)
    - name: Change theme
      lineinfile:
        path: ~/.zshrc
        search_string: ZSH_THEME="robbyrussell"
        line: ZSH_THEME="agnoster"
    - name: Check for zplug
      shell: if [ -d ~/.zplug ]; then echo 'yes'; else echo 'no'; fi
      register: zplug_installed
    - name: Install zplug
      when: zplug_installed.stdout.find("no") != -1
      shell: zsh -c "curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh"
    - name: Add code to .zshrc
      blockinfile:
        path: ~/.zshrc
        block: |
          # My aliases
          alias mkf="make format"
          alias mkc="make check"
          alias mkt="make test"
          alias aptu="sudo apt update && sudo apt upgrade -y && sudo apt autoremove"

          # Zplug block
          autoload -Uz compinit && compinit
          source ~/.zplug/init.zsh
          zplug "woefe/git-prompt.zsh", use:"{git-prompt.zsh,examples/wprompt.zsh}"
          if ! zplug check --verbose; then
              printf "Install? [y/N]: "
              if read -q; then
                  echo; zplug install
              fi
          fi
          zplug load

          # Update PATH
          export "PATH=$PATH:/usr/local/go/bin"

    # tmux
    - name: Install tmux plugin manager
      git:
        repo: https://github.com/tmux-plugins/tpm
        dest: ~/.tmux/plugins/tpm

    # neovim
    - name: Download neovim
      get_url:
        url: https://github.com/neovim/neovim-releases/releases/download/stable/nvim-linux-x86_64.deb
        dest: /tmp/
    - name: Install neovim
      become: true
      apt:
        deb: /tmp/nvim-linux-x86_64.deb
        force: yes
    - name: Install npm packages
      become: true
      npm:
        name: "{{ item }}"
        global: true
      with_items:
        - typescript
        - dockerfile-language-server-nodejs
        - yaml-language-server
        - bash-language-server

    - name: Install plugin manager
      shell: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    - name: Set nvim default git editor
      shell: git config --global core.editor nvim

    - name: Remove dependencies that are no longer required
      become: true
      apt:
        autoremove: yes

    # Hack Nerd Fonts
    - name: Create folder for fonts
      file:
        path: ~/.local/share/fonts
        state: directory
    - name: Download fonts
      unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/Hack.zip
        dest: ~/.local/share/fonts
        remote_src: yes
    - name: Clear fonts cache
      shell: fc-cache -fv
