---
- hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Run apt-get update
    when: apt_update is defined
    become: true
    ignore_errors: yes
    apt:
      update_cache: yes
  - name: Install apt packages
    become: true
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - git
      - vim
      - tmux
      - bat
      - htop
  - name: Install ansible collection
    shell: 'ansible-galaxy collection install community.general && ansible-galaxy collection install community.crypto'
  - name: Set default git user name
    community.general.git_config:
      name: user.name
      scope: global
      value: 'akili'
  - name: Set default git user email
    community.general.git_config:
      name: user.email
      scope: global
      value: 'sedov.anton1986@gmail.com'
  - name: Generate an OpenSSH keypair
    community.crypto.openssh_keypair:
      path: ~/.ssh/id_rsa
