---
- hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Run apt-get update
    when: apt_update is defined
    become: true
    ignore_errors: yes
    apt:
      update_cache: yes
  - name: Install apt packages
    become: true
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - git
      - vim
      - tmux
      - bat
      - htop
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
  - name: Install ansible collection
    shell: 'ansible-galaxy collection install community.general && ansible-galaxy collection install community.crypto'
  - name: Set default git user name
    community.general.git_config:
      name: user.name
      scope: global
      value: 'akili'
  - name: Set default git user email
    community.general.git_config:
      name: user.email
      scope: global
      value: 'sedov.anton1986@gmail.com'
  - name: Create folder for ssh
    file:
      path: ~/.ssh
      state: directory
  - name: Generate an OpenSSH keypair
    community.crypto.openssh_keypair:
      path: ~/.ssh/id_rsa

  # Установка докера
  - name: Add apt-key
    become: true
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
  - name: Add docker repo
    become: true
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
  - name: Install docker
    become: true
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      update_cache: yes
  - name: Add user permissions
    become: true
    shell: "usermod -aG docker {{ lookup('env','USER') }}"
