---
- hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Run apt-get update
    when: apt_update is defined
    become: true
    ignore_errors: yes
    apt:
      update_cache: yes
  - name: Install apt packages
    become: true
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - git
      - vim
      - tmux
      - bat
      - htop
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - build-essential
      - zsh
      - stow
      - tig
      - npm
      - fzf
      - python3-pip
      - exuberant-ctags
      - ripgrep
  - name: Install ansible collection
    shell: 'ansible-galaxy collection install community.general && ansible-galaxy collection install community.crypto'
  - name: Set default git user name
    community.general.git_config:
      name: user.name
      scope: global
      value: 'akili'
  - name: Set default git user email
    community.general.git_config:
      name: user.email
      scope: global
      value: 'sedov.anton1986@gmail.com'
  - name: Create folder for ssh
    file:
      path: ~/.ssh
      state: directory
  - name: Generate an OpenSSH keypair
    community.crypto.openssh_keypair:
      path: ~/.ssh/id_rsa

  # Установка докера
  - name: Add apt-key
    become: true
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
  - name: Add docker repo
    become: true
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
  - name: Install docker
    become: true
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      update_cache: yes
  - name: Add user permissions
    become: true
    shell: "usermod -aG docker {{ lookup('env','USER') }}"
  - name: Install docker-compose
    become: true
    pip:
      name: docker-compose
  - name: Install poetry
    become: true
    pip:
      name: poetry

  # zsh
  - name: Make zsh default shell
    become: true
    shell: 'chsh -s /usr/bin/zsh akili'
  - name: Register oh-my-zsh folder
    stat:
      path: "~/.oh-my-zsh"
    register: ohmyzsh
  - name: Install oh-my-zsh
    shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    when: not ohmyzsh.stat.exists

  # tmux
  - name: Install tmux plugin manager
    git:
      repo: 'https://github.com/tmux-plugins/tpm'
      dest: '~/.tmux/plugins/tpm'

  # neovim
  - name: Install neovim
    become: true
    shell: snap install nvim --classic
  - name: Install npm packages
    become: true
    shell: npm -g install pyright typescript-language-server typescript
  - name: Install plugin manager
    shell: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

